HamburgerMVC4/Areas/Admin/Controllers/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using HamburgerMVC4.Data;

namespace HamburgerMVC4.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class CategoriesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CategoriesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Admin/Categories
        public async Task<IActionResult> Index()
        {
            return View(await _context.Categories.ToListAsync());
        }

        // GET: Admin/Categories/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await _context.Categories
                .FirstOrDefaultAsync(m => m.Id == id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        // GET: Admin/Categories/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Admin/Categories/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name")] Category category)
        {
            if (ModelState.IsValid)
            {
                _context.Add(category);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(category);
        }

        // GET: Admin/Categories/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await _context.Categories.FindAsync(id);
            if (category == null)
            {
                return NotFound();
            }
            return View(category);
        }

        // POST: Admin/Categories/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name")] Category category)
        {
            if (id != category.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(category);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CategoryExists(category.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(category);
        }

        // GET: Admin/Categories/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await _context.Categories
                .FirstOrDefaultAsync(m => m.Id == id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        // POST: Admin/Categories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var category = await _context.Categories.FindAsync(id);
            if (category != null)
            {
                _context.Categories.Remove(category);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CategoryExists(int id)
        {
            return _context.Categories.Any(e => e.Id == id);
        }
    }
}

HamburgerMVC4/Areas/Admin/Controllers/DrinksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using HamburgerMVC4.Data;
using HamburgerMVC4.Areas.Admin.Models;

namespace HamburgerMVC4.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class DrinksController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly Drink _drink;

        public DrinksController(ApplicationDbContext context, Drink drink)
        {
            _context = context;
            _drink = drink;
        }

        // GET: Admin/Drinks
        public async Task<IActionResult> Index()
        {
            return View(await _context.Drinks.ToListAsync());
        }

        // GET: Admin/Drinks/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var drink = await _context.Drinks
                .FirstOrDefaultAsync(m => m.Id == id);
            if (drink == null)
            {
                return NotFound();
            }
            ViewBag.Image = drink.Image;
            return View(drink);
        }

        // GET: Admin/Drinks/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Admin/Drinks/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Image,ImagePath")] DrinkViewModel drinkViewModel)
        {
            if (ModelState.IsValid)
            {
                _drink.Name = drinkViewModel.Name;
                if (drinkViewModel.Image != null)
                {
                    string ext = Path.GetExtension(drinkViewModel.Image.FileName);
                    string newFile = Guid.NewGuid() + ext;
                    string path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "image", "drinks", newFile);
                    using (FileStream fs = new FileStream(path, FileMode.CreateNew))
                    {
                        drinkViewModel.Image.CopyTo(fs);
                    }
                    _drink.Image = newFile;
                    _context.Add(_drink);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
            }
            ViewBag.ErrorMessage = "Please select a image";
            return View(drinkViewModel);
        }

        // GET: Admin/Drinks/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var drink = await _context.Drinks.FindAsync(id);
            if (drink == null)
            {
                return NotFound();
            }
            DrinkViewModel drinkVm = new()
            {
                Id = drink.Id,
                Name = drink.Name,
                ImagePath = drink.Image
            };
            return View(drinkVm);
        }

        // POST: Admin/Drinks/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit([Bind("Id,Name,Image,ImagePath")] DrinkViewModel drinkVm)
        {
            Drink updated = _context.Drinks.Find(drinkVm.Id)!;
            if (updated == null)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                try
                {
                    updated.Name = drinkVm.Name;
                    if (drinkVm.Image != null)
                    {
                        string oldFile = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "image", "drinks", updated.Image);
                        System.IO.File.Delete(oldFile);
                        string ext = Path.GetExtension(drinkVm.Image.FileName);
                        string newFile = Guid.NewGuid() + ext;
                        string path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "image", "drinks", newFile);
                        using (FileStream fs = new FileStream(path, FileMode.CreateNew))
                        {
                            drinkVm.Image.CopyTo(fs);
                        }
                        updated.Image = newFile;
                    }
                    _context.Update(updated);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DrinkExists((int)drinkVm.Id!))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(drinkVm);
        }

        // GET: Admin/Drinks/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var drink = await _context.Drinks
                .FirstOrDefaultAsync(m => m.Id == id);
            if (drink == null)
            {
                return NotFound();
            }
            return View(drink);
        }

        // POST: Admin/Drinks/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var drink = await _context.Drinks.FindAsync(id);
            if (drink != null)
            {
                _context.Drinks.Remove(drink);
                string path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "image", "drinks", drink.Image);
                System.IO.File.Delete(path);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DrinkExists(int id)
        {
            return _context.Drinks.Any(e => e.Id == id);
        }
    }
}

HamburgerMVC4/Areas/Admin/Controllers/MenusController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using HamburgerMVC4.Data;
using HamburgerMVC4.Areas.Admin.Models;
using static System.Net.Mime.MediaTypeNames;
using HamburgerMVC4.Areas.Admin.Data;

namespace HamburgerMVC4.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class MenusController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly Menu _menu;

        public MenusController(ApplicationDbContext context, Menu menu)
        {
            _menu = menu;
            _context = context;
        }

        // GET: Admin/Menus
        public async Task<IActionResult> Index()
        {
            return View(await _context.Menus.Include(m => m.Category).ToListAsync());
        }

        // GET: Admin/Menus/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var menu = await _context.Menus
                .FirstOrDefaultAsync(m => m.Id == id);
            if (menu == null)
            {
                return NotFound();
            }

            return View(menu);
        }

        // GET: Admin/Menus/Create
        public IActionResult Create()
        {
            ViewBag.Categories = _context.Categories.ToList();
            return View();
        }

        // POST: Admin/Menus/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Description,UnitPrice,Image,CategoryId")] MenuViewModel menuViewModel)
        {
            if (menuViewModel != null)
            {
                if (ModelState.IsValid && menuViewModel.Image != null)
                {

                    _menu.Name = menuViewModel.Name;
                    _menu.Image = ImageHandler.CreateImage(menuViewModel.Image,"menus");
                    _menu.UnitPrice = menuViewModel.UnitPrice;
                    _menu.Description = menuViewModel.Description;
                    _menu.CategoryId = menuViewModel.CategoryId;
                    _context.Add(_menu);
                    await _context.SaveChangesAsync();
                    return RedirectToAction("Index");

                }
                ViewBag.ErrorMessage = "Please select a image!";
                ViewBag.Categories = _context.Categories.ToList();
                return View(menuViewModel);
            }
            else return NotFound();

        }

        // GET: Admin/Menus/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var menu = await _context.Menus.FindAsync(id);
            TempData["Id"] = id;
            if (menu == null)
            {
                return NotFound();
            }
            MenuViewModel menuViewModel = new()
            {
                Description = menu.Description,
                Name = menu.Name,
                UnitPrice = menu.UnitPrice,
                CategoryId = menu.CategoryId,
            };
            ViewBag.Image = menu.Image;
            ViewBag.Categories = _context.Categories.ToList();
            return View(menuViewModel);
        }

        // POST: Admin/Menus/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit([Bind("Id,Name,Description,UnitPrice,Image,CategoryId")] MenuViewModel menuViewModel)
        {
            Menu updated = _context.Menus.Find(TempData["Id"]);

            if (updated == null)
            {
                return NotFound();
            }
            ModelState.Remove("Image");
            if (ModelState.IsValid)
            {
                try
                {
                    if (menuViewModel.Image != null)
                    {                      
                        updated.Image = ImageHandler.EditImage(menuViewModel.Image,"menus", updated.Image);
                    }

                    updated.UnitPrice = menuViewModel.UnitPrice;
                    updated.Description = menuViewModel.Description;
                    updated.Name = menuViewModel.Name;
                    updated.CategoryId = menuViewModel.CategoryId;

                    _context.Update(updated);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MenuExists(updated.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewBag.Categories = _context.Categories.ToList();
            return View(menuViewModel);
        }

        // GET: Admin/Menus/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var menu = await _context.Menus
                .FirstOrDefaultAsync(m => m.Id == id);
            if (menu == null)
            {
                return NotFound();
            }

            return View(menu);
        }

        // POST: Admin/Menus/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var menu = await _context.Menus.FindAsync(id);
            if (menu != null)
            {
                _context.Menus.Remove(menu);
            }
            string file = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/image", menu.Image);
            System.IO.File.Delete(file);

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MenuExists(int id)
        {
            return _context.Menus.Any(e => e.Id == id);
        }

    }
}

HamburgerMVC4/Areas/Admin/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>@ViewBag.Title - Easy Blog Administration</title>
    <link href="https://cdn.jsdelivr.net/npm/simple-datatables@7.1.2/dist/style.min.css" rel="stylesheet" />
    <link href="~/admin/css/styles.css" rel="stylesheet" />
    <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Kristi&display=swap" rel="stylesheet">
</head>
<body class="sb-nav-fixed">
    <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark py-5">
        <!-- Sidebar Toggle-->
        <button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0 ms-2" id="sidebarToggle" href="#!"><i class="fas fa-bars"></i></button>
        <!-- Navbar Brand-->
        <div class="d-flex flex-row logo ms-4">
            <a class="navbar-brand fs-1" asp-area="" asp-controller="Home" asp-action="Index">
                <img style="height: 50px" src="~/image/logo.png" alt="Logo">Boost Burger
            </a>
        </div>

        <ul class="navbar-nav ms-auto me-0 me-md-3 my-2 my-md-0">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
                <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                    <li><a class="dropdown-item" asp-area="Identity" asp-controller="Account" asp-action="Manage">Settings</a></li>
                    <li><hr class="dropdown-divider" /></li>
                    <li>
                        <form class="form-inline dropdown-item" asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "" })">
                            <button type="submit" class="customLink nav-link btn btn-link text-dark">Logout</button>
                        </form>
                    </li>
                </ul>
            </li>
        </ul>
    </nav>
    <div id="layoutSidenav">
        <div id="layoutSidenav_nav">
            <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                <div class="sb-sidenav-menu mt-4">
                    <div class="nav">
                        <div class="sb-sidenav-menu-heading">Administration</div>
                        <a class="nav-link" asp-area="Admin" asp-controller="Dashboard" asp-action="Index">
                            <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                            Dashboard
                        </a>
                        <div class="sb-sidenav-menu-heading">Content</div>
                        <a class="nav-link" href="#" data-bs-toggle="collapse" data-bs-target="#collapseCategories" aria-expanded="false" aria-controls="collapseCategories">
                            <div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>
                            Categories
                            <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                        </a>
                        <div class="collapse show" id="collapseCategories" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordion">
                            <nav class="sb-sidenav-menu-nested nav">
                                <a class="nav-link" asp-controller="Categories" asp-action="Index">List All</a>
                                <a class="nav-link" asp-controller="Categories" asp-action="Create">Add New</a>
                            </nav>
                        </div>
                        <a class="nav-link" href="#" data-bs-toggle="collapse" data-bs-target="#collapseMenus" aria-expanded="false" aria-controls="collapseMenus">
                            <div class="sb-nav-link-icon"><i class="fa-solid fa-burger"></i></div>
                            Menus
                            <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                        </a>
                        <div class="collapse show" id="collapseMenus" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordion">
                            <nav class="sb-sidenav-menu-nested nav">
                                <a class="nav-link" asp-controller="Menus" asp-action="Index">List All</a>
                                <a class="nav-link" asp-controller="Menus" asp-action="Create">Add New</a>
                            </nav>
                        </div>
                        <a class="nav-link" href="#" data-bs-toggle="collapse" data-bs-target="#collapseDrinks" aria-expanded="false" aria-controls="collapseDrinks">
                            <div class="sb-nav-link-icon"><i class="fa-solid fa-whiskey-glass"></i></div>
                            Drinks
                            <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                        </a>
                        <div class="collapse show" id="collapseDrinks" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordion">
                            <nav class="sb-sidenav-menu-nested nav">
                                <a class="nav-link" asp-controller="Drinks" asp-action="Index">List All</a>
                                <a class="nav-link" asp-controller="Drinks" asp-action="Create">Add New</a>
                            </nav>
                        </div>
                        <a class="nav-link" href="#" data-bs-toggle="collapse" data-bs-target="#collapseExtras" aria-expanded="false" aria-controls="collapseExtras">
                            <div class="sb-nav-link-icon"><i class="fa-solid fa-wine-bottle"></i></i></div>
                            Extras
                            <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                        </a>
                        <div class="collapse show" id="collapseExtras" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordion">
                            <nav class="sb-sidenav-menu-nested nav">
                                <a class="nav-link" asp-controller="Extras" asp-action="Index">List All</a>
                                <a class="nav-link" asp-controller="Extras" asp-action="Create">Add New</a>
                            </nav>
                        </div>
                    </div>
                </div>
                <div class="sb-sidenav-footer">
                    <div class="small">Logged in as:</div>
                    @User.Identity!.Name
                </div>
            </nav>
        </div>
        <div id="layoutSidenav_content">
            <main>
                <div class="container-fluid px-4 mt-5">
                    @RenderBody()
                </div>
            </main>
            <footer class="py-4 bg-light mt-auto">
                <div class="container-fluid px-4">
                    <div class="d-flex align-items-center justify-content-between small">
                        <div class="text-muted">Copyright &copy; Easy Blog 2024</div>
                        <div>
                            <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy Policy</a>
                            &middot;
                            <a href="#">Terms &amp; Conditions</a>
                        </div>
                    </div>
                </div>
            </footer>
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
    <script src="~/admin/js/scripts.js"></script>
    @* <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script> *@
    <script src="https://cdn.jsdelivr.net/npm/simple-datatables@7.1.2/dist/umd/simple-datatables.min.js" crossorigin="anonymous"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    @await RenderSectionAsync("Scripts", false)
</body>
</html>