HamburgerMVC4/Areas/Admin/Models/ExtraViewModel.cs
using HamburgerMVC4.Attributes;
using HamburgerMVC4.Data;

namespace HamburgerMVC4.Areas.Admin.Models
{
    public class ExtraViewModel
    {
        public int? Id { get; set; }
        public string Name { get; set; } = null!;
        public string? ImagePath { get; set; } = null!;
        public double UnitPrice { get; set; }
    }
}

HamburgerMVC4/Areas/Admin/Controllers/ExtrasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using HamburgerMVC4.Data;
using HamburgerMVC4.Areas.Admin.Models;

namespace HamburgerMVC4.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class ExtrasController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly Extra _extra;

        public ExtrasController(ApplicationDbContext context, Extra extra)
        {
            _context = context;
            _extra = extra;
        }

        // GET: Admin/Extras
        public async Task<IActionResult> Index()
        {
            return View(await _context.Extras.ToListAsync());
        }

        // GET: Admin/Extras/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var extra = await _context.Extras
                .FirstOrDefaultAsync(m => m.Id == id);
            if (extra == null)
            {
                return NotFound();
            }

            return View(extra);
        }

        // GET: Admin/Extras/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Admin/Extras/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,UnitPrice")] ExtraViewModel extraVm)
        {
            if (ModelState.IsValid)
            {
                _extra.Name = extraVm.Name;
                _extra.UnitPrice = extraVm.UnitPrice;
            
                
                    _context.Add(_extra);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                
            }         
            return View(extraVm);
        }

        // GET: Admin/Extras/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var extra = await _context.Extras.FindAsync(id);
            if (extra == null)
            {
                return NotFound();
            }
            ExtraViewModel extraVm = new()
            {
                Id = extra.Id,
                Name = extra.Name,
                UnitPrice = extra.UnitPrice,            
            };
            return View(extraVm);
        }

        // POST: Admin/Extras/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit([Bind("Id,Name,UnitPrice")] ExtraViewModel extraVm)
        {
            Extra updated = _context.Extras.Find(extraVm.Id)!;
            if (updated == null)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    updated.Name = extraVm.Name;
                    updated.UnitPrice = extraVm.UnitPrice;
                                      
                    
                    _context.Update(updated);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ExtraExists((int)extraVm.Id!))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(extraVm);
        }

        // GET: Admin/Extras/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var extra = await _context.Extras
                .FirstOrDefaultAsync(m => m.Id == id);
            if (extra == null)
            {
                return NotFound();
            }

            return View(extra);
        }

        // POST: Admin/Extras/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var extra = await _context.Extras.FindAsync(id);
            if (extra != null)
            {
                _context.Extras.Remove(extra);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ExtraExists(int id)
        {
            return _context.Extras.Any(e => e.Id == id);
        }
    }
}

HamburgerMVC4/Areas/Admin/Views/Extras/Create.cshtml
@model ExtraViewModel

@{
    ViewData["Title"] = "Create";
}
<div style="margin-top:150px; padding:50px" class="container detail-card">
    <h1 style="font-family:Kristi; font-size:4rem;" class="detail-card">Create Extra</h1>

    <hr />
    <div class="row">
        <div class="col-md-12">
            <form asp-action="Create" enctype="multipart/form-data">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="mb-3">
                    <label asp-for="Name" class="control-label"></label>
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <label asp-for="UnitPrice" class="control-label"></label>
                    <input type="number" asp-for="UnitPrice" class="form-control" />
                    <span asp-validation-for="UnitPrice" class="text-danger"></span>
                </div>
                <div class="mb-3">
                </div>
                <div class="d-flex justify-content-between">
                <div class="mb-3">
                    <input type="submit" value="Create" class="btn btn-primary" />
                </div>
                <div>
                    <a class="btn btn-secondary" asp-action="Index">Back to List</a>
                </div>

                </div>
            </form>
        </div>
    </div>

</div>
@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

HamburgerMVC4/Areas/Admin/Views/Extras/Delete.cshtml
@model HamburgerMVC4.Data.Extra

@{
    ViewData["Title"] = "Delete";
}

<div style="margin-top:150px; padding:50px;" class="container detail-card">

    <h3>Are you sure you want to delete this?</h3>
    <hr />
    <div>
        <dl class="row">

            <dt class="col-sm-2 mb-3">
                @Html.DisplayNameFor(model => model.Name)
            </dt>
            <dd class="col-sm-10 mb-3">
                @Html.DisplayFor(model => model.Name)
            </dd>
        </dl>

        <form asp-action="Delete">
            <input type="hidden" asp-for="Id" />
            <input type="submit" value="Delete" class="btn btn-danger" />
            <a class="btn btn-secondary" asp-action="Index">Back to List</a>
        </form>
    </div>
</div>

HamburgerMVC4/Areas/Admin/Views/Extras/Details.cshtml
@model HamburgerMVC4.Data.Extra

@{
    ViewData["Title"] = "Details";
}


<div style="margin-top:150px; padding:50px;" class="container detail-card">

    <h1 class="detail-card" style="font-family:Kristi; font-size:4rem;">Extra Details</h1>

    <div class="detail-card">
        <div class="row">
            <div class="col-md-12 mt-3">
                <p style="margin-bottom:3px">@Html.DisplayNameFor(model => model.Name) : @Model.Name</p>
                <p>@Html.DisplayNameFor(model => model.UnitPrice): @Model.UnitPrice₺ </p>
                <div>
                    <a class="btn btn-warning" asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> 
                    <a class="btn btn-secondary" asp-action="Index">Back to List</a>
                </div>

            </div>
        
        </div>

    </div>
</div>

HamburgerMVC4/Areas/Admin/Views/Extras/Edit.cshtml
@model ExtraViewModel

@{
    ViewData["Title"] = "Edit";
}



<div style="margin-top:150px; padding:50px;" class="container detail-card">
    <h1 class="detail-card" style="font-family:Kristi; font-size:4rem;">Extra Edit</h1>
    <hr />
    <div class="row">
        <div class="col-md-12">
            <form asp-action="Edit" enctype="multipart/form-data">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="Id" />
                <div class="mb-3">
                    <label asp-for="Name" class="control-label"></label>
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <label asp-for="UnitPrice" class="control-label"></label>
                    <input type="number" asp-for="UnitPrice" class="form-control" />
                    <span asp-validation-for="UnitPrice" class="text-danger"></span>
                </div>
                <div class="mb-3">
                </div>
                <div class="d-flex justify-content-between">
                <div class="mb-3">
                    <input type="submit" value="Save" class="btn btn-primary" />
                </div>
                <div>
                    <a class="btn btn-secondary" asp-action="Index">Back to List</a>
                </div>
                </div>
            </form>
        </div>
    </div>


    @section Scripts {
        @{
            await Html.RenderPartialAsync("_ValidationScriptsPartial");
        }
    }

HamburgerMVC4/Areas/Admin/Views/Extras/Index.cshtml
@model IEnumerable<HamburgerMVC4.Data.Extra>

@{
    ViewData["Title"] = "Index";
}


<div class="container-fluid pt-4 px-4">
    <h2 style="font-family:Kristi; font-size:3rem;">All Extras</h2>
    <div class="d-flex justify-content-end p-4">
        <a class="btn btn-success btn-lg mt-2" asp-action="Create">Create New</a>
    </div>
    <div class="bg-light text-center rounded p-4">
        <div class="d-flex align-items-center justify-content-between mb-4">
        </div>
        <div class="table-responsive">
            <table class="table text-start align-middle table-bordered table-hover mb-0">
                <thead>
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.Name)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.UnitPrice)
                        </th>

                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@item.Name</td>
                            <td>@item.UnitPrice₺ </td>
                            <td class="col-1 ">
                                <div class="d-flex justify-content-around">
                                    <a class="btn btn-warning mb-1" asp-controller="Extras" asp-action="Edit" asp-route-id="@item.Id"><i class="fa-solid fa-pen-to-square"></i></a>
                                    <a class="btn btn-secondary mb-1" asp-controller="Extras" asp-action="Details" asp-route-id="@item.Id"><i class="fa-solid fa-circle-info"></i></a>
                                    <a class="btn btn-danger" asp-controller="Extras" asp-action="Delete" asp-route-id="@item.Id"><i class="fa-solid fa-trash"></i></a>
                                </div>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>